require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe KingdomsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Kingdom. As you add validations to Kingdom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Fungus' }
  }

  let(:invalid_attributes) {
    { name: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KingdomsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all kingdoms as @kingdoms" do
      kingdom = Kingdom.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:kingdoms)).to eq([kingdom])
    end
  end

  describe "GET show" do
    it "assigns the requested kingdom as @kingdom" do
      kingdom = Kingdom.create! valid_attributes
      get :show, {:id => kingdom.to_param}, valid_session
      expect(assigns(:kingdom)).to eq(kingdom)
    end
  end

  describe "GET new" do
    it "assigns a new kingdom as @kingdom" do
      get :new, {}, valid_session
      expect(assigns(:kingdom)).to be_a_new(Kingdom)
    end
  end

  describe "GET edit" do
    it "assigns the requested kingdom as @kingdom" do
      kingdom = Kingdom.create! valid_attributes
      get :edit, {:id => kingdom.to_param}, valid_session
      expect(assigns(:kingdom)).to eq(kingdom)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Kingdom" do
        expect {
          post :create, {:kingdom => valid_attributes}, valid_session
        }.to change(Kingdom, :count).by(1)
      end

      it "assigns a newly created kingdom as @kingdom" do
        post :create, {:kingdom => valid_attributes}, valid_session
        expect(assigns(:kingdom)).to be_a(Kingdom)
        expect(assigns(:kingdom)).to be_persisted
      end

      it "redirects to the created kingdom" do
        post :create, {:kingdom => valid_attributes}, valid_session
        expect(response).to redirect_to(Kingdom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kingdom as @kingdom" do
        post :create, {:kingdom => invalid_attributes}, valid_session
        expect(assigns(:kingdom)).to be_a_new(Kingdom)
      end

      it "re-renders the 'new' template" do
        post :create, {:kingdom => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { name: 'Animal' }
      }

      it "updates the requested kingdom" do
        kingdom = Kingdom.create! valid_attributes
        put :update, {:id => kingdom.to_param, :kingdom => new_attributes}, valid_session
        kingdom.reload
        expect(assigns(:kingdom)).to eq(kingdom)
      end

      it "assigns the requested kingdom as @kingdom" do
        kingdom = Kingdom.create! valid_attributes
        put :update, {:id => kingdom.to_param, :kingdom => valid_attributes}, valid_session
        expect(assigns(:kingdom)).to eq(kingdom)
      end

      it "redirects to the kingdom" do
        kingdom = Kingdom.create! valid_attributes
        put :update, {:id => kingdom.to_param, :kingdom => valid_attributes}, valid_session
        expect(response).to redirect_to(kingdom)
      end
    end

    describe "with invalid params" do
      it "assigns the kingdom as @kingdom" do
        kingdom = Kingdom.create! valid_attributes
        put :update, {:id => kingdom.to_param, :kingdom => invalid_attributes}, valid_session
        expect(assigns(:kingdom)).to eq(kingdom)
      end

      it "re-renders the 'edit' template" do
        kingdom = Kingdom.create! valid_attributes
        put :update, {:id => kingdom.to_param, :kingdom => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kingdom" do
      kingdom = Kingdom.create! valid_attributes
      expect {
        delete :destroy, {:id => kingdom.to_param}, valid_session
      }.to change(Kingdom, :count).by(-1)
    end

    it "redirects to the kingdoms list" do
      kingdom = Kingdom.create! valid_attributes
      delete :destroy, {:id => kingdom.to_param}, valid_session
      expect(response).to redirect_to(kingdoms_url)
    end
  end

end
